-- Enqueue 2023 tranche candidates into v2 executions using policy hit gates.
--
-- Policy:
--   >=0.60      : queue (core category)
--   0.55-0.60   : queue (core category)
--   0.50-0.55   : queue if combined_hits >= 1
--   0.40-0.50   : queue if combined_hits >= 2
--   <0.40       : skip
--
-- combined_hits = direct term hits over title+abstract using:
--   - 2023 organic cleaned word-cloud terms
--   - 2023 best-anchor terms from scored rows (dynamic)
--
-- Run from research_paper_analysis_v2 root:
--   sqlite3 data/v2_executions.sqlite < queries/enqueue_2023_all_tranches_pending.sql

PRAGMA busy_timeout = 120000;
ATTACH DATABASE '../arxiv_crawler/data/arxiv.sqlite' AS arxiv;
BEGIN;

DROP TABLE IF EXISTS to_insert;
CREATE TEMP TABLE to_insert AS
WITH
core_categories(cat) AS (
  VALUES
    ('cs.LG'),('cs.CL'),('cs.AI'),('cs.CV'),('cs.IR'),('cs.NE'),
    ('stat.ML'),('cs.MA'),('cs.SD'),('eess.AS'),('eess.IV')
),
wc_terms(term) AS (
  VALUES
    ('0-1 loss'),
    ('1.2 million'),
    ('1.3 billion'),
    ('1.5 million'),
    ('1.5 times'),
    ('1.8 times'),
    ('10x faster'),
    ('13b 70b'),
    ('13b parameter'),
    ('175b parameter'),
    ('2-3 times'),
    ('2-wasserstein distance'),
    ('2.0 dataset'),
    ('2.5 times'),
    ('2/3 regret'),
    ('21st century'),
    ('3x faster'),
    ('4-bit quantization'),
    ('4-bit weight'),
    ('4.0 license'),
    ('4d radar'),
    ('5g beyond'),
    ('5g network'),
    ('5g radio'),
    ('5g wireless'),
    ('6-dof grasp'),
    ('6d object'),
    ('6d object pose'),
    ('6d pose'),
    ('6d poses'),
    ('6g mobile'),
    ('6g network'),
    ('6g wireless'),
    ('7-dof robot'),
    ('7b 13b'),
    ('7b parameter'),
    ('a100 gpu'),
    ('a100 gpus'),
    ('accuracy'),
    ('activation patching'),
    ('actor-critic'),
    ('adam optimizer'),
    ('adapters'),
    ('adversarial attack'),
    ('adversarial defense'),
    ('adversarial training'),
    ('agent'),
    ('agentic'),
    ('ai alignment'),
    ('ai safety'),
    ('alignment'),
    ('alpacaeval'),
    ('analogical reasoning'),
    ('apache 2.0'),
    ('arc'),
    ('attention mechanism'),
    ('attention visualization'),
    ('attribution'),
    ('audio-language'),
    ('autoregressive'),
    ('backdoor attack'),
    ('backpropagation'),
    ('bart t5'),
    ('batch inference'),
    ('batch normalization'),
    ('benchmark'),
    ('bert'),
    ('bert gpt-2'),
    ('bf16'),
    ('bidirectional'),
    ('big-bench'),
    ('bleu'),
    ('block sparse attention'),
    ('bm25'),
    ('c&w attack'),
    ('calibration'),
    ('capabilitie gpt-4'),
    ('catastrophic forgetting'),
    ('causal attention'),
    ('causal reasoning'),
    ('certified robustness'),
    ('chain of thought'),
    ('chain-of-thought'),
    ('chatgpt 3.5'),
    ('chatgpt gpt-3'),
    ('chatgpt gpt-3.5'),
    ('chatgpt gpt-3.5 gpt-4'),
    ('chatgpt gpt-4'),
    ('chatgpt gpt4'),
    ('chatgpt-3.5 chatgpt-4'),
    ('cifar10 cifar100'),
    ('cifar10 dataset'),
    ('cifar100 dataset'),
    ('circuit analysis'),
    ('class-incremental'),
    ('claude'),
    ('clip'),
    ('co2 emission'),
    ('colbert'),
    ('commonsense reasoning'),
    ('comparative feedback'),
    ('compared gpt-4'),
    ('concept activation'),
    ('constitutional ai'),
    ('content filtering'),
    ('context window'),
    ('continual learning'),
    ('contrastive learning'),
    ('contriever'),
    ('conversational ai'),
    ('cross-lingual transfer'),
    ('cross-modal attention'),
    ('curriculum learning'),
    ('d4rl benchmark'),
    ('data augmentation'),
    ('data contamination'),
    ('data curation'),
    ('data filtering'),
    ('data parallelism'),
    ('data poisoning'),
    ('dataset 100k'),
    ('dataset cifar10'),
    ('dataset gpt-4'),
    ('decoder-only'),
    ('decomposition'),
    ('deduplication'),
    ('deliberation'),
    ('dense retrieval'),
    ('dense transformer'),
    ('device-to-device d2d'),
    ('dialogue systems'),
    ('diffusion'),
    ('diffusion transformer'),
    ('distillation'),
    ('distribution shift'),
    ('document chunking'),
    ('document understanding'),
    ('domain adaptation'),
    ('domain shift'),
    ('dpo'),
    ('dropout'),
    ('e2e asr'),
    ('e2e model'),
    ('edge deployment'),
    ('elastic weight consolidation'),
    ('ell_0 norm'),
    ('ell_1 ell_2'),
    ('ell_1 norm'),
    ('ell_1 regularization'),
    ('ell_2 error'),
    ('ell_2 norm'),
    ('embedding layer'),
    ('embedding model'),
    ('embedding similarity'),
    ('encoder-decoder'),
    ('encoder-only'),
    ('end-to-end e2e'),
    ('era5 reanalysi'),
    ('evaluation'),
    ('evaluation gpt-4'),
    ('evasion attack'),
    ('experience replay'),
    ('experiment cifar10'),
    ('experiment gpt-4'),
    ('explainable ai'),
    ('f-1 score'),
    ('f1 score'),
    ('f_1 score'),
    ('factuality'),
    ('falcon'),
    ('feature attribution'),
    ('feed-forward network'),
    ('few-shot learning'),
    ('fgsm'),
    ('find gpt-4'),
    ('fine-tuned t5'),
    ('fine-tuning'),
    ('flash attention'),
    ('found gpt-4'),
    ('foundation model'),
    ('fp16'),
    ('function calling'),
    ('gemini'),
    ('gemini pro vision'),
    ('glue'),
    ('gpt'),
    ('gpt 3.5'),
    ('gpt-2 gpt-3'),
    ('gpt-2 model'),
    ('gpt-2 small'),
    ('gpt-3 chatgpt'),
    ('gpt-3 gpt-3.5'),
    ('gpt-3 gpt-4'),
    ('gpt-3 model'),
    ('gpt-3.5 gpt-4'),
    ('gpt-3.5 model'),
    ('gpt-3.5 turbo'),
    ('gpt-3.5-turbo gpt-4'),
    ('gpt-4 ability'),
    ('gpt-4 achieve'),
    ('gpt-4 achieved'),
    ('gpt-4 also'),
    ('gpt-4 chatgpt'),
    ('gpt-4 claude'),
    ('gpt-4 code'),
    ('gpt-4 demonstrate'),
    ('gpt-4 demonstrated'),
    ('gpt-4 evaluation'),
    ('gpt-4 exhibit'),
    ('gpt-4 gpt-3.5'),
    ('gpt-4 human'),
    ('gpt-4 large'),
    ('gpt-4 llama'),
    ('gpt-4 model'),
    ('gpt-4 more'),
    ('gpt-4 perform'),
    ('gpt-4 prompt'),
    ('gpt-4 result'),
    ('gpt-4 shown'),
    ('gpt-4 was'),
    ('gpt-4 which'),
    ('gpt-4v'),
    ('gpt-4v ision'),
    ('gpt3.5 gpt4'),
    ('gradient checkpointing'),
    ('gradient descent'),
    ('grapheme-to-phoneme g2p'),
    ('gsm8k'),
    ('gsm8k math'),
    ('guardrails'),
    ('hallucination'),
    ('harmlessness'),
    ('hellaswag'),
    ('helpfulness'),
    ('honesty'),
    ('human feedback'),
    ('human gpt-4'),
    ('human-ai interaction'),
    ('human3.6m mpi-inf-3dhp'),
    ('humaneval'),
    ('hybrid search'),
    ('image captioning'),
    ('in-context learning'),
    ('incremental learning'),
    ('industry 4.0'),
    ('inference optimization'),
    ('instruction data'),
    ('instruction following'),
    ('instruction tuning'),
    ('int4'),
    ('int8'),
    ('integrated gradients'),
    ('interactive learning'),
    ('interpretability'),
    ('jailbreak'),
    ('jailbreaking'),
    ('knowledge base'),
    ('knowledge distillation'),
    ('knowledge graph'),
    ('kv cache'),
    ('l1 l2'),
    ('l2 regularization'),
    ('l_2 norm'),
    ('language model'),
    ('language model gpt-3'),
    ('language model gpt-4'),
    ('large language model'),
    ('large language model gpt-4'),
    ('latency'),
    ('layernorm'),
    ('learning rate schedule'),
    ('less than 0.1'),
    ('leverage gpt-4'),
    ('leveraging gpt-4'),
    ('lifelong learning'),
    ('lime'),
    ('llama'),
    ('llama 7b'),
    ('llama-2 model'),
    ('llava'),
    ('llm'),
    ('llm gpt-3.5'),
    ('llm gpt-4'),
    ('lmsys arena'),
    ('logical reasoning'),
    ('long context'),
    ('lora'),
    ('masked language modeling'),
    ('mathcal 1/k'),
    ('mathcal 1/t'),
    ('mathematical reasoning'),
    ('mechanistic interpretability'),
    ('metacognition'),
    ('mistral'),
    ('mixed precision'),
    ('mixtral'),
    ('mixture of experts'),
    ('mmlu'),
    ('mobile ai'),
    ('model compression'),
    ('model pruning'),
    ('model serving'),
    ('moe'),
    ('mpt'),
    ('mt-bench'),
    ('multi-head attention'),
    ('multi-step reasoning'),
    ('multi-task learning'),
    ('multimodal'),
    ('multimodal fusion'),
    ('nvidia a100'),
    ('nvidia a100 gpu'),
    ('nvidia v100'),
    ('ocr'),
    ('olmo'),
    ('on-device ai'),
    ('online learning'),
    ('onnx'),
    ('openai gpt-3'),
    ('openai gpt-3.5'),
    ('openai gpt-4'),
    ('palm'),
    ('parameter-efficient fine-tuning'),
    ('peer-to-peer p2p'),
    ('perplexity'),
    ('pgd'),
    ('phi'),
    ('pipeline parallelism'),
    ('planning'),
    ('poisoning attack'),
    ('policy gradient'),
    ('positional encoding'),
    ('ppo'),
    ('pre-training'),
    ('pre-training data'),
    ('preference data'),
    ('preference learning'),
    ('prefix tuning'),
    ('pretraining'),
    ('probing'),
    ('progressive nets'),
    ('prompt engineering'),
    ('prompt gpt-4'),
    ('prompt tuning'),
    ('prompting gpt-4'),
    ('pruning'),
    ('ptq'),
    ('qat'),
    ('qlora'),
    ('qm9 dataset'),
    ('quantization'),
    ('quantized inference'),
    ('query expansion'),
    ('qwen'),
    ('r2 score'),
    ('rag'),
    ('randomized smoothing'),
    ('rate 1/2'),
    ('real-time inference'),
    ('reasoning'),
    ('reasoning traces'),
    ('red teaming'),
    ('reflection'),
    ('refusal training'),
    ('representation analysis'),
    ('reranking'),
    ('residual connections'),
    ('result gpt-4'),
    ('retrieval'),
    ('retrieval augmented generation'),
    ('retrieval-augmented generation'),
    ('reward hacking'),
    ('reward model'),
    ('reward modeling'),
    ('rlhf'),
    ('roberta t5'),
    ('rouge'),
    ('safety cases'),
    ('saliency maps'),
    ('scalar feedback'),
    ('scaling law'),
    ('self attention'),
    ('self-attention'),
    ('self-consistency'),
    ('self-critique'),
    ('self-supervised learning'),
    ('semantic search'),
    ('seq2seq model'),
    ('sequence-to-sequence seq2seq'),
    ('sequence-to-sequence seq2seq model'),
    ('serving infrastructure'),
    ('shap'),
    ('sim2real gap'),
    ('sim2real transfer'),
    ('sixth-generation 6g'),
    ('softmax'),
    ('sparse attention'),
    ('sparse autoencoders'),
    ('sparse moe'),
    ('sparse retrieval'),
    ('specifically gpt-4'),
    ('specification gaming'),
    ('speculative decoding'),
    ('speech recognition'),
    ('speech-to-speech translation s2st'),
    ('squad 2.0'),
    ('superglue'),
    ('superposition'),
    ('supervised fine-tuning'),
    ('supervised fine-tuning (sft)'),
    ('sycophancy'),
    ('synthetic data'),
    ('t2i diffusion'),
    ('t2i diffusion model'),
    ('t2i generation'),
    ('t2i model'),
    ('t5'),
    ('t5 bart'),
    ('t5 model'),
    ('task-incremental'),
    ('tensor parallelism'),
    ('tensorrt'),
    ('test-time adaptation'),
    ('text-to-speech'),
    ('text-to-video t2v'),
    ('tgi'),
    ('than 0.1'),
    ('than 0.5'),
    ('than gpt-3.5'),
    ('than gpt-4'),
    ('throughput'),
    ('tilde 1/2'),
    ('tilde 2/3'),
    ('token prediction'),
    ('tokenization'),
    ('tool use'),
    ('transfer learning'),
    ('transformer'),
    ('transformer gpt-4'),
    ('transformer t5'),
    ('translation s2st'),
    ('tree of thoughts'),
    ('truthfulqa'),
    ('unicode x2013'),
    ('unicode x2014'),
    ('unitree a1'),
    ('up 1.5'),
    ('up 10x'),
    ('up 20x'),
    ('up 2x'),
    ('up 3x'),
    ('up 4x'),
    ('up 5x'),
    ('up 6x'),
    ('user intent'),
    ('v100 gpu'),
    ('v100 gpus'),
    ('v2 dataset'),
    ('v2v communication'),
    ('v2x communication'),
    ('vector database'),
    ('vehicle-to-everything v2x'),
    ('vehicle-to-vehicle v2v'),
    ('vgg16 vgg19'),
    ('video understanding'),
    ('vision transformer (vit)'),
    ('vision-language'),
    ('vision-language model'),
    ('visual grounding'),
    ('vllm'),
    ('vqa'),
    ('warmup'),
    ('wav2vec 2.0'),
    ('weight decay'),
    ('while gpt-4'),
    ('winogrande'),
    ('yolov5 model'),
    ('yolov8 model'),
    ('zero-shot learning')
),
anchor_terms(term) AS (
  SELECT DISTINCT LOWER(json_extract(pr.details_json, '$.best_anchor')) AS term
  FROM arxiv.papers p
  JOIN arxiv.paper_relevance pr ON pr.paper_id = p.id
  WHERE p.arxiv_id LIKE '23%'
    AND pr.fmr_2023 IS NOT NULL
    AND json_extract(pr.details_json, '$.best_anchor') IS NOT NULL
),
all_terms(term) AS (
  SELECT term FROM wc_terms
  UNION
  SELECT term FROM anchor_terms WHERE term IS NOT NULL AND term <> ''
),
base AS (
  SELECT
    p.arxiv_id,
    p.id AS paper_id,
    COALESCE(p.title, '') AS title,
    COALESCE(p.abstract, '') AS abstract,
    pr.fmr_2023 AS score
  FROM arxiv.papers p
  JOIN arxiv.paper_relevance pr ON pr.paper_id = p.id
  WHERE p.arxiv_id LIKE '23%'
    AND p.llm_relevant = 1
    AND p.primary_category IN (SELECT cat FROM core_categories)
    AND pr.fmr_2023 IS NOT NULL
    AND pr.fmr_2023 >= 0.40
    AND NOT EXISTS (
      SELECT 1 FROM executions e WHERE e.arxiv_id = p.arxiv_id
    )
),
scored_hits AS (
  SELECT
    b.*,
    (
      SELECT COUNT(*)
      FROM all_terms t
      WHERE INSTR(LOWER(b.title || ' ' || b.abstract), t.term) > 0
    ) AS combined_hits
  FROM base b
)
SELECT
  s.*,
  CASE
    WHEN s.score >= 0.60 THEN '>=0.60'
    WHEN s.score >= 0.55 THEN '0.55-0.60'
    WHEN s.score >= 0.50 THEN '0.50-0.55'
    WHEN s.score >= 0.40 THEN '0.40-0.50'
    ELSE '<0.40'
  END AS tranche
FROM scored_hits s
WHERE
  s.score >= 0.55
  OR (s.score >= 0.50 AND s.score < 0.55 AND s.combined_hits >= 1)
  OR (s.score >= 0.40 AND s.score < 0.50 AND s.combined_hits >= 2);

SELECT tranche, COUNT(*) AS candidates
FROM to_insert
GROUP BY tranche
ORDER BY CASE tranche
  WHEN '>=0.60' THEN 1
  WHEN '0.55-0.60' THEN 2
  WHEN '0.50-0.55' THEN 3
  WHEN '0.40-0.50' THEN 4
  ELSE 5
END;

INSERT OR IGNORE INTO executions (
  execution_id,
  arxiv_id,
  paper_id,
  title,
  authors,
  abstract,
  status,
  created_at,
  updated_at,
  prep_output,
  result_path,
  error,
  priority
)
SELECT
  LOWER(HEX(RANDOMBLOB(16))) AS execution_id,
  t.arxiv_id,
  t.paper_id,
  t.title,
  '' AS authors,
  t.abstract,
  'pending' AS status,
  STRFTIME('%Y-%m-%dT%H:%M:%f+00:00','now') AS created_at,
  STRFTIME('%Y-%m-%dT%H:%M:%f+00:00','now') AS updated_at,
  NULL AS prep_output,
  NULL AS result_path,
  NULL AS error,
  CASE
    WHEN t.score >= 0.55 THEN t.score
    ELSE t.score + (0.001 * MIN(t.combined_hits, 20))
  END AS priority
FROM to_insert t
ORDER BY priority DESC, t.score DESC;

SELECT changes() AS inserted_rows;

DROP TABLE to_insert;
COMMIT;
DETACH DATABASE arxiv;
