spec: flatprofile
spec_version: 4.1.0
data:
  model_profiles:
    structured:
      name: openrouter/google/gemma-4-26b-a4b-it:free
    reasoning:
      name: openrouter/google/gemma-4-26b-a4b-it:free
  default: structured
